version: '3'
services:
  app:
    build:
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: Sogen0921
      MYSQL_USER: root
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Bookingdam
      - public-data:/Bookingdam/public
      - tmp-data:/Bookingdam/tmp
      - log-data:/Bookingdam/log
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: Sogen0921
      MYSQL_USER: root
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: 
      context: containers/nginx
    volumes:
      - public-data:/Bookingdam/public
      - tmp-data:/Bookingdam/tmp
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: