version: 2

jobs: # ステップの集合
  build: # Workflows を使用しない実行では、エントリポイントとして `build` ジョブが必要
    docker: # Docker でステップを実行します
      - image: circleci/ruby:2.6.2 # このイメージをすべての `steps` が実行されるプライマリコンテナとして使用します
        environment: # プライマリコンテナの環境変数
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: <%= ENV['MYSQL_PASSWORD'] %>
          MYSQL_USER: root
      - image: circleci/mysql:5.6 # データベースイメージ
    working_directory: ~/Bookingdam
    steps:
      - checkout

      - run:
          name: bundle install
          command: |
              gem install bundler -v 2.1.4
              bundle install --path vendor/bundle
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: |
              bundle exec rake db:create
              bundle exec rake db:schema:load
      - run: 
          name: テストの実行
          command: bundle exec rspec

      - run:
          name: Rubocop実行
          command: bundle exec rubocop
  

workflows:
  version: 2
  workflows:
    jobs:
      - build