version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers-legacy
        environment:
            RAILS_ENV: test
            DB_HOST: 127.0.0.1
            DB_USERNAME: 'root'
            DB_PASSWORD: '<%= ENV['MYSQL_PASSWORD'] %>'
      - image: circleci/mysql:5.6
    working_directory: ~/Bookingdam

    steps:
      - checkout
      - run:
        name: bundle install
        command: bundle install 
    - run:
        name: データベースの起動を待機
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
    - run:
        name: データベースのセットアップ
        command: bundle exec rake db:schema:load
    - run: 
        name: テストの実行
        command: bundle exec rspec
    - run:
        name: コード解析
        command: bundle exec rubocop

workflows:
  version: 2
  workflows:
    jobs:
      - test